name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libxerces-c-dev libx11-dev libgl1-mesa-dev


    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build
